## 作業:
作業目標，讓大家熟悉連續型分配的語法，
以及怎麼透過 python 語法進行常態分配的機率運算。


### Q1:計算標準常態分配，小於1的機率有多大?
![](Q1.png)

In [9]:
# library
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy import stats
import math
import statistics
import seaborn as sns

In [39]:
## Q1
#  提示: 用 cdf 來算
# hist 概率
# bin_edges 邊界
mu=0
sigma=1
s = np.random.normal(mu, sigma, 1000)
hist, bin_edges = np.histogram(s, density=True)
hist, bin_edges, hist[np.where(bin_edges<1)[0]][-1]

(array([0.00301657, 0.01206628, 0.06636453, 0.1975853 , 0.31221494,
        0.37857947, 0.29411552, 0.1583699 , 0.07541424, 0.01055799]),
 array([-3.63225501, -2.96925022, -2.30624543, -1.64324064, -0.98023585,
        -0.31723105,  0.34577374,  1.00877853,  1.67178332,  2.33478811,
         2.9977929 ]),
 0.29411552154339377)

### Q2:計算標準常態分配，大於1，小於 -1 的機率有多大?
![](Q2.png)


In [38]:
## Q2
np.where(bin_edges>1)[0]

array([ 7,  8,  9, 10], dtype=int64)

### Q3:X~N(2,4),x 服從常態分配，平均數為2,變異數為 4，計算 X小於 6 的機率有多大?

In [4]:
## Q3
#  提示: 和 Q1,Q2 不同，要先標準化。
'''
你的程式碼
'''

'\n你的程式碼\n'